name: OneClickTests-Update
  
run-name: >
  Update workspace from old version test.

on:
  push:
  pull_request:
    types: [opened, reopened, synchronize]
    paths-ignore:
      - '.github/**'
      - 'tests/**'
      - '**/README.md'

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:

      - name: Set matrix names
        id: set-matrix
        run: |
          matrix=$(echo '{
            "include": [
              {"execute": '${{ github.event.inputs.centos7 || true }}', "name": "CentOS7", "os": "centos7", "distr": "onlyoffice"},
              {"execute": '${{ github.event.inputs.centos8s || true }}', "name": "CentOS8S", "os": "centos8s", "distr": "onlyoffice"},
              {"execute": '${{ github.event.inputs.centos9s || true }}', "name": "CentOS9S", "os": "centos9s", "distr": "onlyoffice"},
              {"execute": '${{ github.event.inputs.debian10 || true }}', "name": "Debian10", "os": "debian10", "distr": "onlyoffice"},
              {"execute": '${{ github.event.inputs.debian11 || true }}', "name": "Debian11", "os": "debian11", "distr": "onlyoffice"},
              {"execute": '${{ github.event.inputs.debian12 || true }}', "name": "Debian12", "os": "debian12", "distr": "onlyoffice"},
              {"execute": '${{ github.event.inputs.ubuntu1804 || true }}', "name": "Ubuntu18.04", "os": "ubuntu1804", "distr": "onlyoffice"},
              {"execute": '${{ github.event.inputs.ubuntu2004 || true }}', "name": "Ubuntu20.04", "os": "ubuntu2004", "distr": "onlyoffice"},
              {"execute": '${{ github.event.inputs.ubuntu2204 || true }}', "name": "Ubuntu22.04", "os": "ubuntu2204", "distr": "onlyoffice"}
            ]
          }' | jq -c '{include: [.include[] | select(.execute == true)]}')
          echo "matrix=${matrix}" >> $GITHUB_OUTPUT

  update-test:
    name: "Update test on ${{ matrix.name }}"
    runs-on: ubuntu-latest
    #if: ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
    needs: prepare
    strategy:
      fail-fast: false
      matrix: ${{fromJSON(needs.prepare.outputs.matrix)}}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Testing with update
      uses: nick-fields/retry@v2
      with:
        max_attempts: 1
        timeout_minutes: 80
        retry_on: error
        command: |
              cd ./tests/vagrant
              set -eux

              TEST_CASE='--local-install' \
              DISTR='${{matrix.distr}}' \
              RAM='6100' \
              CPU='3' \
              OS='${{ matrix.os }}' \
              DOWNLOAD_SCRIPT='-ds false' \
              TEST_REPO='-tr true' \
              ARGUMENTS="-arg '--skiphardwarecheck true --makeswap false --localscripts true --update true'" \
              vagrant up
              sleep 10
              vagrant destroy --force
        on_retry_command: |
             set -eux
             echo "Clean-up and one more try"
             cd ./tests/vagrant
             vagrant destroy --force

